version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - FRED_API_KEY=${FRED_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    depends_on:
      - test
    networks:
      - trading-network

  # Testing service
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run test:ci
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - FRED_API_KEY=test_key_for_testing
      - ALPHA_VANTAGE_API_KEY=test_key_for_testing
    networks:
      - trading-network

  # Linting service
  lint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run lint
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge

volumes:
  node_modules: